---
- name: CHECK TELNET
  hosts: route-server.he.net
  gather_facts: false
  connection: local


  tasks:

    - name: CHECK IS TELNET IS UP
      wait_for:
        port: 23
        state: started
        timeout: 1000
        host: "{{ inventory_hostname }}"
