---
- name: CHECK TELNET
  hosts: localhost
  gather_facts: false
  connection: local


  tasks:

    - name: CHECK IS TELNET IS UP
      wait_for:
        port: 23
        state: started
        timeout: 3
        host: "{{ inventory_hostname }}"
        
    - name: pause for 5 seconds
      pause:
        seconds: 5
        
    - name: collect facts
      setup:
        register: facts

    - name: print all facts
      debug: var=facts
        
    
